import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Menu from './Components/navMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={inter.className}>
          <nav>
            <Link href='/User'>User Page</Link>
            <span>     </span> 
            <Link href='/Main'>Main Page</Link>
            <Menu />   
          </nav>
          {children}
      </body>
    </html>
  )
}
